version: '3.7'
services:
  app:
    container_name: app
    ports:
      - 8081:8081
      - 9100:9100
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    network_mode: bridge
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
      - ./src/logs:/usr/src/app/src/logs
    command: npm run dev
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped 
    network_mode: bridge
    expose:
      - 6379  
    volumes:
      - ./redis-volume:/data
  